text_classifier:
    _target_: text_classification.core.classifiers.TextClassifier
    model_path: "./models/lstm_sentiment/model.keras"
    tokenizer_path: "./models/lstm_sentiment/tokenizer.pickle"
    labels:
        - "Négatif"
        - "Positif"

text_preprocessor:
    _target_: text_classification.core.preprocessing.TextPreprocessor
    language: "english"

api:
    version: "1.0.0"
    title: "Sentiment Analysis API"
    description: "API for sentiment analysis"
    host: "localhost"
    port: 8000
