name: Build and Publish Python Wheel to GitHub Packages

on:
  push:
    branches:
      - main  # Change to your branch if different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Specify Python 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build the wheel
        run: python -m build

      - name: Publish to GitHub Packages
        env:
          TWINE_USERNAME: ${{ github.actor }}
          TWINE_PASSWORD: ${{ secrets.GH_TOKEN }}
        run: |
          twine upload --repository-url https://upload.pypi.org/legacy/ dist/*
