name: End-to-End Testing

on: [push, pull_request]

jobs:
  e2e-test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: konverner/text_classification:latest
        ports:
          - 8000:80
        options: > 
          --health-cmd "curl --fail http://localhost:80/classify || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install Bruno
      run: pip install bruno

    - name: Wait for Docker to be healthy
      run: |
        echo "Waiting for Docker to be healthy..."
        while ! docker inspect --format='{{json .State.Health.Status}}' konverner/text_classification | grep healthy; do
          sleep 1;
        done

    - name: Run Bruno tests
      run: bruno run tests/bruno
