name: End-to-End Testing

on: [push, pull_request]

jobs:
  e2e-test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: konverner/text_classification:latest
        ports:
          - 8000:8000
        options: > 
          --health-cmd="curl --fail http://localhost:8000/classify || exit 1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install Bruno
      run: pip install bruno

    - name: Wait for Docker to be healthy
      id: wait_for_service
      uses: elgohr/Wait-For-Container-Action@v2
      with:
        time: 60
        retries: 10
        test: curl --fail http://localhost:8000/classify

    - name: Run Bruno tests
      run: bruno run tests/bruno
